language: objective-c

addons:
  homebrew:
    packages:
    - openssl

script:
  - xcodebuild build -project Samples/DynamicServer/DynamicServer.xcodeproj -scheme DynamicServer
  - xcodebuild build -project Samples/iPhoneHTTPServer/iPhoneHTTPServer.xcodeproj -scheme iPhoneHTTPServer -sdk iphonesimulator
  - xcodebuild build -project Samples/PasswdHTTPServer/PasswdHTTPServer.xcodeproj -scheme PasswdHTTPServer
  - xcodebuild build -project Samples/PostHTTPServer/PostHTTPServer.xcodeproj -scheme PostHTTPServer
  - xcodebuild build -project Samples/SecureHTTPServer/SecureHTTPServer.xcodeproj -scheme SecureHTTPServer
  - xcodebuild build -project Samples/SecureWebSocketServer/SecureWebSocketServer.xcodeproj -scheme SecureWebSocketServer
  - xcodebuild build -project Samples/SimpleFileUploadServer/SimpleFileUploadServer.xcodeproj -scheme SimpleFileUploadServer
  - xcodebuild build -project Samples/SimpleHTTPServer/SimpleHTTPServer.xcodeproj -scheme SimpleHTTPServer
  - xcodebuild build -project Samples/SimpleWebSocketServer/SimpleWebSocketServer.xcodeproj -scheme SimpleWebSocketServer
